ERROR: 03-16 16:56:52: webpage_urlopen.py:68 * 34156 Fail to webpage_urlopen for url(http://www.wuhan.gov.cn/whszf_45/whszwgk/zcfg) as unknowException: ''
ERROR: 03-16 16:56:52: webpage_urlopen.py:53 * 34792 Fail to webpage_urlopen for url(http://www.hangzhou.gov.cn/col/col933522/index.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:56:52: webpage_urlopen.py:62 * 34792 Fail to webpage_urlopen for url(http://www.hangzhou.gov.cn/col/col933522/index.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:56:52: webpage_urlopen.py:56 * 34632 Fail to webpage_urlopen for url(http://www.sz.gov.cn/cn/xxgk/zfxxgj/zcjd) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:56:52: webpage_urlopen.py:62 * 34632 Fail to webpage_urlopen for url(http://www.sz.gov.cn/cn/xxgk/zfxxgj/zcjd) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:56:53: webpage_urlopen.py:62 * 34792 Fail to webpage_urlopen for url(http://www.changsha.gov.cn/xxgk/szfxxgkml/zfwj2016/zfwj/szfwj1) as HTTPError: HTTP Error 461: 
ERROR: 03-16 16:56:53: webpage_urlopen.py:68 * 7548 Fail to webpage_urlopen for url(http://gtog.ningbo.gov.cn/col/col390/index.html) as unknowException: ''
WARNING: 03-16 16:56:54: webpage_urlopen.py:42 * 7548 Fail to match charset Regex for url:http://www.harbin.gov.cn/zwxxgk/zcjd/list.jsp?urltype=tree.TreeTempUrl&wbtreeid=4697, using the default charset.
ERROR: 03-16 16:56:58: webpage_urlopen.py:53 * 34156 Fail to webpage_urlopen for url(http://www.jiaxing.gov.cn/zwxx/zcwj_10001) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:56:58: webpage_urlopen.py:62 * 34156 Fail to webpage_urlopen for url(http://www.jiaxing.gov.cn/zwxx/zcwj_10001) as HTTPError: HTTP Error 403: Forbidden
WARNING: 03-16 16:56:59: webpage_urlopen.py:42 * 36808 Fail to match charset Regex for url:http://www.guilin.gov.cn/zfxxgk/ztxxgk/bdzcjd, using the default charset.
ERROR: 03-16 16:56:59: webpage_urlopen.py:56 * 8340 Fail to webpage_urlopen for url(http://www.huhhot.gov.cn/zw/more.asp?b_id=110308) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:56:59: webpage_urlopen.py:62 * 8340 Fail to webpage_urlopen for url(http://www.huhhot.gov.cn/zw/more.asp?b_id=110308) as HTTPError: HTTP Error 404: Not Found
WARNING: 03-16 16:57:00: webpage_urlopen.py:42 * 34792 Fail to match charset Regex for url:http://www.bd.gov.cn/list-1031-137-list.html, using the default charset.
WARNING: 03-16 16:57:00: webpage_urlopen.py:42 * 36808 Fail to match charset Regex for url:http://www.zhangzhou.gov.cn/cms/html/zzsrmzf/zcjd/index.html, using the default charset.
WARNING: 03-16 16:57:01: webpage_urlopen.py:42 * 7548 Fail to match charset Regex for url:http://www.linyi.gov.cn/gk/zwgk_list_lanmu.jsp?urltype=tree.TreeTempUrl&wbtreeid=1103, using the default charset.
WARNING: 03-16 16:57:03: webpage_urlopen.py:42 * 7548 Fail to match charset Regex for url:http://www.baotou.gov.cn/hdjl/zcjd.htm, using the default charset.
ERROR: 03-16 16:57:05: webpage_urlopen.py:64 * 34156 Fail to webpage_urlopen for url(http://gk.wh.cn/xxgkweb/blue/index.jsp?type=mulu&unit=003010829&xxfl_id=040400&sort=1) as URLError: <urlopen error timed out>
ERROR: 03-16 16:57:06: webpage_urlopen.py:64 * 36172 Fail to webpage_urlopen for url(http://www.ganzhou.gov.cn/zwgk/cyxx/fggw/zcjd) as URLError: <urlopen error timed out>
WARNING: 03-16 16:57:06: webpage_urlopen.py:42 * 8340 Fail to match charset Regex for url:http://www.daqing.gov.cn/zfgw/zcjd/index.shtml, using the default charset.
ERROR: 03-16 16:57:55: webpage_urlopen.py:53 * 25012 Fail to webpage_urlopen for url(http://www.hangzhou.gov.cn/col/col933522/index.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:57:55: webpage_urlopen.py:62 * 25012 Fail to webpage_urlopen for url(http://www.hangzhou.gov.cn/col/col933522/index.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:57:55: webpage_urlopen.py:68 * 34076 Fail to webpage_urlopen for url(http://www.wuhan.gov.cn/whszf_45/whszwgk/zcfg) as unknowException: ''
ERROR: 03-16 16:57:55: webpage_urlopen.py:56 * 26668 Fail to webpage_urlopen for url(http://www.sz.gov.cn/cn/xxgk/zfxxgj/zcjd) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:57:55: webpage_urlopen.py:62 * 26668 Fail to webpage_urlopen for url(http://www.sz.gov.cn/cn/xxgk/zfxxgj/zcjd) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:57:56: webpage_urlopen.py:62 * 36500 Fail to webpage_urlopen for url(http://www.changsha.gov.cn/xxgk/szfxxgkml/zfwj2016/zfwj/szfwj1) as HTTPError: HTTP Error 461: 
ERROR: 03-16 16:57:57: webpage_urlopen.py:68 * 30628 Fail to webpage_urlopen for url(http://gtog.ningbo.gov.cn/col/col390/index.html) as unknowException: ''
WARNING: 03-16 16:57:58: webpage_urlopen.py:42 * 11368 Fail to match charset Regex for url:http://www.harbin.gov.cn/zwxxgk/zcjd/list.jsp?urltype=tree.TreeTempUrl&wbtreeid=4697, using the default charset.
ERROR: 03-16 16:58:01: webpage_urlopen.py:53 * 34076 Fail to webpage_urlopen for url(http://www.jiaxing.gov.cn/zwxx/zcwj_10001) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:58:01: webpage_urlopen.py:62 * 34076 Fail to webpage_urlopen for url(http://www.jiaxing.gov.cn/zwxx/zcwj_10001) as HTTPError: HTTP Error 403: Forbidden
WARNING: 03-16 16:58:03: webpage_urlopen.py:42 * 34076 Fail to match charset Regex for url:http://www.guilin.gov.cn/zfxxgk/ztxxgk/bdzcjd, using the default charset.
ERROR: 03-16 16:58:03: webpage_urlopen.py:56 * 36500 Fail to webpage_urlopen for url(http://www.huhhot.gov.cn/zw/more.asp?b_id=110308) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:58:03: webpage_urlopen.py:62 * 36500 Fail to webpage_urlopen for url(http://www.huhhot.gov.cn/zw/more.asp?b_id=110308) as HTTPError: HTTP Error 404: Not Found
WARNING: 03-16 16:58:04: webpage_urlopen.py:42 * 11812 Fail to match charset Regex for url:http://www.bd.gov.cn/list-1031-137-list.html, using the default charset.
WARNING: 03-16 16:58:04: webpage_urlopen.py:42 * 36500 Fail to match charset Regex for url:http://www.zhangzhou.gov.cn/cms/html/zzsrmzf/zcjd/index.html, using the default charset.
WARNING: 03-16 16:58:05: webpage_urlopen.py:42 * 36500 Fail to match charset Regex for url:http://www.linyi.gov.cn/gk/zwgk_list_lanmu.jsp?urltype=tree.TreeTempUrl&wbtreeid=1103, using the default charset.
ERROR: 03-16 16:58:07: webpage_urlopen.py:64 * 26668 Fail to webpage_urlopen for url(http://www.ly.gov.cn/zwgk/zfxxgkml/index.shtml) as URLError: <urlopen error timed out>
WARNING: 03-16 16:58:08: webpage_urlopen.py:42 * 25012 Fail to match charset Regex for url:http://www.baotou.gov.cn/hdjl/zcjd.htm, using the default charset.
ERROR: 03-16 16:58:09: webpage_urlopen.py:64 * 34076 Fail to webpage_urlopen for url(http://gk.wh.cn/xxgkweb/blue/index.jsp?type=mulu&unit=003010829&xxfl_id=040400&sort=1) as URLError: <urlopen error timed out>
ERROR: 03-16 16:58:09: webpage_urlopen.py:64 * 11368 Fail to webpage_urlopen for url(http://www.ganzhou.gov.cn/zwgk/cyxx/fggw/zcjd) as URLError: <urlopen error timed out>
WARNING: 03-16 16:58:10: webpage_urlopen.py:42 * 11812 Fail to match charset Regex for url:http://www.daqing.gov.cn/zfgw/zcjd/index.shtml, using the default charset.
WARNING: 03-16 16:58:11: webpage_urlopen.py:42 * 11812 Fail to match charset Regex for url:http://www.chifeng.gov.cn/xxgk/dtxx/zcjdsx, using the default charset.
ERROR: 03-16 16:58:12: webpage_urlopen.py:62 * 11812 Fail to webpage_urlopen for url(http://www.czs.gov.cn/html/zwgk/fggw/wjjd/15292/default.htm) as HTTPError: HTTP Error 461: 
WARNING: 03-16 16:58:13: webpage_urlopen.py:42 * 26668 Fail to match charset Regex for url:http://www.np.gov.cn/cms/html/npszf/ghjd/index.html, using the default charset.
ERROR: 03-16 16:58:14: webpage_urlopen.py:66 * 25012 Fail to webpage_urlopen for url(http://www.jlcity.gov.cn/jlszf_web/xxgk/zfwj.jsp?lmid=10010030010&flmid=10010030010) as IOError: timed out
ERROR: 03-16 16:58:14: webpage_urlopen.py:53 * 34704 Fail to webpage_urlopen for url(http://www.bengbu.gov.cn/zdzcjd) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:58:14: webpage_urlopen.py:62 * 34704 Fail to webpage_urlopen for url(http://www.bengbu.gov.cn/zdzcjd) as HTTPError: HTTP Error 403: Forbidden
WARNING: 03-16 16:58:14: webpage_urlopen.py:42 * 11812 Fail to match charset Regex for url:http://www.xianyang.gov.cn/info/iList.jsp?cat_id=25583, using the default charset.
WARNING: 03-16 16:58:15: webpage_urlopen.py:42 * 11368 Fail to match charset Regex for url:http://www.qqhr.gov.cn/News_showFlzyNewsList.action?messagekey=8, using the default charset.
ERROR: 03-16 16:58:15: webpage_urlopen.py:68 * 34076 Fail to webpage_urlopen for url(www.xingtai.gov.cn/zwgk/zwdt/gsgg) as unknowException: unknown url type: www.xingtai.gov.cn/zwgk/zwdt/gsgg
ERROR: 03-16 16:58:17: webpage_urlopen.py:64 * 26668 Fail to webpage_urlopen for url(https://www.meizhou.gov.cn/zwgk/fggw/wjjd/index.htm) as URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
ERROR: 03-16 16:58:17: webpage_urlopen.py:68 * 11368 Fail to webpage_urlopen for url(http://www.danyang.gov.cn/dyfront/xxgk/DepartMent/?DeptCode=001&TabID=1&CategoryNum=001021) as unknowException: 'gb18030' codec can't decode bytes in position 15345-15346: illegal multibyte sequence
WARNING: 03-16 16:58:18: webpage_urlopen.py:42 * 36500 Fail to match charset Regex for url:http://xxgk.linfen.gov.cn/LF00100/LF00100/channels/4916.html, using the default charset.
ERROR: 03-16 16:58:18: webpage_urlopen.py:53 * 34076 Fail to webpage_urlopen for url(http://www.jiangmen.gov.cn/zwgk/fggk/zcjd) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:58:18: webpage_urlopen.py:62 * 34076 Fail to webpage_urlopen for url(http://www.jiangmen.gov.cn/zwgk/fggk/zcjd) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:58:18: webpage_urlopen.py:64 * 30628 Fail to webpage_urlopen for url(http://www.liuzhou.gov.cn/xxgk/jcxxgk/zcwj/zcjd) as URLError: <urlopen error timed out>
ERROR: 03-16 16:58:18: webpage_urlopen.py:53 * 11368 Fail to webpage_urlopen for url(http://www.weinan.gov.cn/info/iList.jsp?tm_id=1442&cat_id=140) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:58:18: webpage_urlopen.py:62 * 11368 Fail to webpage_urlopen for url(http://www.weinan.gov.cn/info/iList.jsp?tm_id=1442&cat_id=140) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:58:19: webpage_urlopen.py:62 * 11368 Fail to webpage_urlopen for url(http://www.lishui.gov.cn/zwgk/zwxxgk/002645662/4/zcjd) as HTTPError: HTTP Error 461: 
ERROR: 03-16 16:58:55: webpage_urlopen.py:53 * 33988 Fail to webpage_urlopen for url(http://www.hangzhou.gov.cn/col/col933522/index.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:58:55: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.hangzhou.gov.cn/col/col933522/index.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:58:55: webpage_urlopen.py:68 * 14396 Fail to webpage_urlopen for url(http://www.wuhan.gov.cn/whszf_45/whszwgk/zcfg) as unknowException: ''
ERROR: 03-16 16:58:55: webpage_urlopen.py:56 * 36728 Fail to webpage_urlopen for url(http://www.sz.gov.cn/cn/xxgk/zfxxgj/zcjd) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:58:55: webpage_urlopen.py:62 * 36728 Fail to webpage_urlopen for url(http://www.sz.gov.cn/cn/xxgk/zfxxgj/zcjd) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:58:56: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.changsha.gov.cn/xxgk/szfxxgkml/zfwj2016/zfwj/szfwj1) as HTTPError: HTTP Error 461: 
ERROR: 03-16 16:58:56: webpage_urlopen.py:68 * 10128 Fail to webpage_urlopen for url(http://gtog.ningbo.gov.cn/col/col390/index.html) as unknowException: ''
WARNING: 03-16 16:58:58: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.harbin.gov.cn/zwxxgk/zcjd/list.jsp?urltype=tree.TreeTempUrl&wbtreeid=4697, using the default charset.
ERROR: 03-16 16:59:01: webpage_urlopen.py:53 * 13052 Fail to webpage_urlopen for url(http://www.jiaxing.gov.cn/zwxx/zcwj_10001) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:01: webpage_urlopen.py:62 * 13052 Fail to webpage_urlopen for url(http://www.jiaxing.gov.cn/zwxx/zcwj_10001) as HTTPError: HTTP Error 403: Forbidden
WARNING: 03-16 16:59:03: webpage_urlopen.py:42 * 13052 Fail to match charset Regex for url:http://www.guilin.gov.cn/zfxxgk/ztxxgk/bdzcjd, using the default charset.
ERROR: 03-16 16:59:03: webpage_urlopen.py:56 * 14396 Fail to webpage_urlopen for url(http://www.huhhot.gov.cn/zw/more.asp?b_id=110308) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:03: webpage_urlopen.py:62 * 14396 Fail to webpage_urlopen for url(http://www.huhhot.gov.cn/zw/more.asp?b_id=110308) as HTTPError: HTTP Error 404: Not Found
WARNING: 03-16 16:59:03: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.bd.gov.cn/list-1031-137-list.html, using the default charset.
WARNING: 03-16 16:59:04: webpage_urlopen.py:42 * 13052 Fail to match charset Regex for url:http://www.zhangzhou.gov.cn/cms/html/zzsrmzf/zcjd/index.html, using the default charset.
WARNING: 03-16 16:59:05: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.linyi.gov.cn/gk/zwgk_list_lanmu.jsp?urltype=tree.TreeTempUrl&wbtreeid=1103, using the default charset.
WARNING: 03-16 16:59:06: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.baotou.gov.cn/hdjl/zcjd.htm, using the default charset.
ERROR: 03-16 16:59:09: webpage_urlopen.py:64 * 33988 Fail to webpage_urlopen for url(http://gk.wh.cn/xxgkweb/blue/index.jsp?type=mulu&unit=003010829&xxfl_id=040400&sort=1) as URLError: <urlopen error timed out>
WARNING: 03-16 16:59:09: webpage_urlopen.py:42 * 35944 Fail to match charset Regex for url:http://www.daqing.gov.cn/zfgw/zcjd/index.shtml, using the default charset.
ERROR: 03-16 16:59:09: webpage_urlopen.py:64 * 34676 Fail to webpage_urlopen for url(http://www.ganzhou.gov.cn/zwgk/cyxx/fggw/zcjd) as URLError: <urlopen error timed out>
WARNING: 03-16 16:59:11: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.chifeng.gov.cn/xxgk/dtxx/zcjdsx, using the default charset.
ERROR: 03-16 16:59:11: webpage_urlopen.py:62 * 35944 Fail to webpage_urlopen for url(http://www.czs.gov.cn/html/zwgk/fggw/wjjd/15292/default.htm) as HTTPError: HTTP Error 461: 
WARNING: 03-16 16:59:11: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.np.gov.cn/cms/html/npszf/ghjd/index.html, using the default charset.
ERROR: 03-16 16:59:12: webpage_urlopen.py:53 * 35944 Fail to webpage_urlopen for url(http://www.bengbu.gov.cn/zdzcjd) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:12: webpage_urlopen.py:62 * 35944 Fail to webpage_urlopen for url(http://www.bengbu.gov.cn/zdzcjd) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:12: webpage_urlopen.py:68 * 35852 Fail to webpage_urlopen for url(www.xingtai.gov.cn/zwgk/zwdt/gsgg) as unknowException: unknown url type: www.xingtai.gov.cn/zwgk/zwdt/gsgg
WARNING: 03-16 16:59:13: webpage_urlopen.py:42 * 13052 Fail to match charset Regex for url:http://www.qqhr.gov.cn/News_showFlzyNewsList.action?messagekey=8, using the default charset.
WARNING: 03-16 16:59:14: webpage_urlopen.py:42 * 33988 Fail to match charset Regex for url:http://www.xianyang.gov.cn/info/iList.jsp?cat_id=25583, using the default charset.
ERROR: 03-16 16:59:15: webpage_urlopen.py:64 * 13052 Fail to webpage_urlopen for url(https://www.meizhou.gov.cn/zwgk/fggw/wjjd/index.htm) as URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
ERROR: 03-16 16:59:16: webpage_urlopen.py:68 * 36728 Fail to webpage_urlopen for url(http://www.danyang.gov.cn/dyfront/xxgk/DepartMent/?DeptCode=001&TabID=1&CategoryNum=001021) as unknowException: 'gb18030' codec can't decode bytes in position 15345-15346: illegal multibyte sequence
WARNING: 03-16 16:59:16: webpage_urlopen.py:42 * 10128 Fail to match charset Regex for url:http://xxgk.linfen.gov.cn/LF00100/LF00100/channels/4916.html, using the default charset.
ERROR: 03-16 16:59:16: webpage_urlopen.py:53 * 13052 Fail to webpage_urlopen for url(http://www.jiangmen.gov.cn/zwgk/fggk/zcjd) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:16: webpage_urlopen.py:62 * 13052 Fail to webpage_urlopen for url(http://www.jiangmen.gov.cn/zwgk/fggk/zcjd) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:16: webpage_urlopen.py:53 * 14396 Fail to webpage_urlopen for url(http://www.weinan.gov.cn/info/iList.jsp?tm_id=1442&cat_id=140) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:16: webpage_urlopen.py:62 * 14396 Fail to webpage_urlopen for url(http://www.weinan.gov.cn/info/iList.jsp?tm_id=1442&cat_id=140) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:17: webpage_urlopen.py:56 * 35852 Fail to webpage_urlopen for url(http://www.gdqy.gov.cn/gdqy/804zcjd/qy_list1.shtml) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:17: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.gdqy.gov.cn/gdqy/804zcjd/qy_list1.shtml) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:17: webpage_urlopen.py:62 * 14396 Fail to webpage_urlopen for url(http://www.lishui.gov.cn/zwgk/zwxxgk/002645662/4/zcjd) as HTTPError: HTTP Error 461: 
ERROR: 03-16 16:59:18: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.yuxi.gov.cn/yuxi/336119/336544/336695/index.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:18: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.yuxi.gov.cn/yuxi/336119/336544/336695/index.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:18: webpage_urlopen.py:68 * 13052 Fail to webpage_urlopen for url(http://www.liaoyang.gov.cn/mhzcfgjd/index.htm) as unknowException: ''
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201703/t20170309_3588187.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201702/t20170223_3586075.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201702/t20170221_3585617.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201702/t20170208_3584801.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201702/t20170207_3584704.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201702/t20170206_3584604.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201701/t20170126_3584356.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:27: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201701/t20170120_3583407.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:27: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201701/t20170103_3580093.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201612/t20161225_3578744.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201612/t20161215_3576841.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201612/t20161209_3575863.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201612/t20161207_3575505.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201612/t20161202_3574861.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201611/t20161125_3573906.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201611/t20161123_3573444.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 13052 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201611/t20161115_3571756.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201611/t20161114_3571455.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 13052 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201611/t20161111_3571016.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 13052 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201611/t20161111_3571002.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201611/t20161101_3568681.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 13052 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201610/t20161024_3568235.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 13052 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201610/t20161024_3568234.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/zcjd/201610/t20161021_3568114.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 13052 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/tjzc/201703/t20170310_3588472.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 13052 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/tjzc/201703/t20170310_3588472.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 13052 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/tjzc/201703/t20170309_3588214.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/tjzc/201703/t20170309_3588214.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 13052 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/tjzc/201702/t20170227_3586541.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 13052 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:28: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.tj.gov.cn/../zw/tjzc/201702/t20170227_3586541.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 16:59:28: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 228: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 10128 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/gj/) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 10128 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/gj/) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 10128 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 35852 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170311_1207717.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170311_1207717.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 34676 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zctj/) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zctj/) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 10128 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170310_1207243.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 10128 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170310_1207243.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 10128 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 35852 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170307_1205072.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170307_1205072.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 33988 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170303_1203464.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170303_1203464.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 34676 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170302_1202735.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201703/t20170302_1202735.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 35944 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170222_1198642.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 35944 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170222_1198642.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 35944 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 680: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 10128 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170222_1198441.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 10128 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170222_1198441.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 10128 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 378: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 33988 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170221_1197630.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170221_1197630.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 378: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:52: webpage_urlopen.py:56 * 35852 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170221_1198194.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170221_1198194.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:52: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 378: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:56 * 34676 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170213_1192843.htm) as HTTPError(404-Not Found): HTTP Error 404: Not Found
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.fuzhou.gov.cn/zfb/xxgk/zcjd_1/201702/t20170213_1192843.htm) as HTTPError: HTTP Error 404: Not Found
ERROR: 03-16 16:59:53: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 378: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201702/t20170222_6126712.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201702/t20170222_6126712.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 36728 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 378: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201701/t20170122_6107922.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201701/t20170122_6107922.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201701/t20170122_6107893.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 193: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201701/t20170122_6107893.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 193: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 34676 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201612/t20161230_6090194.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201612/t20161230_6090194.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201612/t20161214_6077641.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201612/t20161214_6077641.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 36728 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201611/t20161124_6061035.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201611/t20161124_6061035.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201611/t20161122_6056560.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201611/t20161122_6056560.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 34676 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201610/t20161031_6029925.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201610/t20161031_6029925.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 35944 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201610/t20161014_6013846.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 35944 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201610/t20161014_6013846.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 35944 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 10128 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201610/t20161011_6010706.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 10128 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201610/t20161011_6010706.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 10128 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 14396 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201609/t20160905_5986325.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201609/t20160920_5994920.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201609/t20160901_5983935.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 14396 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201609/t20160905_5986325.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201609/t20160920_5994920.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201609/t20160901_5983935.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 14396 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: readability.py:198 * 36728 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980142.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980142.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 34676 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980079.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 35944 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201607/t20160721_5833686.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980079.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 35944 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201607/t20160721_5833686.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: readability.py:198 * 35944 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 10128 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201607/t20160721_5833682.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 10128 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201607/t20160721_5833682.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 10128 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980088.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 36728 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980088.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 14396 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980090.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 36728 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: webpage_urlopen.py:53 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980096.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 14396 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980090.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: webpage_urlopen.py:62 * 33988 Fail to webpage_urlopen for url(http://www.foshan.gov.cn/zwgk/zcwj/201608/t20160829_5980096.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:53: readability.py:198 * 14396 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
ERROR: 03-16 16:59:53: readability.py:198 * 33988 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseEntityRef: expecting ';'
WARNING: 03-16 16:59:53: webpage_urlopen.py:42 * 35944 Fail to match charset Regex for url:http://www.zzrd.gov.cn, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/zdgcjsxmssjz/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/zdgchssxm/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xzsp/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/czsj_1999/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/gmjjhshfztjxx/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/zfbz/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/spypjdjcqk/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/hjbh/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.suzhou.gov.cn/aqscjdjcqk/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/zsbc/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/zfcg_12356/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/jgsf/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.suzhou.gov.cn/gyjz/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/yjgl/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/rsxx_2010/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/kjww/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.suzhou.gov.cn/ghjh/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xyxx/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/jycy_13970/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/jczwxx/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35944 Fail to match charset Regex for url:http://www.suzhou.gov.cn/gyqyyyjg/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201703/t20170313_852011.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.suzhou.gov.cn/scjg/, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35944 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201702/t20170221_845796.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201703/t20170314_852581.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201703/t20170314_852515.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201702/t20170213_843520.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170125_839911.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 35944 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170125_839921.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170123_839136.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170126_840332.shtml, using the default charset.
WARNING: 03-16 16:59:54: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170126_840333.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170106_834498.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170110_835315.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170125_840059.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 35944 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170113_836264.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170105_834097.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 14396 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201701/t20170106_834283.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 35944 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201612/t20161214_828033.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 35852 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201612/t20161227_831680.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 34676 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201612/t20161226_831555.shtml, using the default charset.
WARNING: 03-16 16:59:55: webpage_urlopen.py:42 * 36728 Fail to match charset Regex for url:http://www.suzhou.gov.cn/xxgk/fggwjjd/zcfgjd/201612/t20161213_827599.shtml, using the default charset.
ERROR: 03-16 16:59:57: webpage_urlopen.py:64 * 13052 Fail to webpage_urlopen for url(http://www.xm.gov.cn/zwgk/wjjd/201607/t20160726_1350820.htm) as URLError: <urlopen error timed out>
ERROR: 03-16 16:59:57: readability.py:198 * 13052 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 267: htmlParseStartTag: misplaced <body> tag
ERROR: 03-16 16:59:59: webpage_urlopen.py:53 * 34676 Fail to webpage_urlopen for url(http://www.shandong.gov.cn/module/classification/dicsearch/dicsearch.jsp) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 16:59:59: webpage_urlopen.py:62 * 34676 Fail to webpage_urlopen for url(http://www.shandong.gov.cn/module/classification/dicsearch/dicsearch.jsp) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 16:59:59: readability.py:198 * 34676 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 113: Unexpected end tag : body
ERROR: 03-16 17:00:00: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/zzjg/) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/zzjg/) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 145: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:00: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/zdxxgk/) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/zdxxgk/) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 127: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:00: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/yjzj/) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:00: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:00: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/fl/) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/fl/) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:00: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/bjwj/) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:00: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:00: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/nnzb/) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/nnzb/) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:00: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170310_721994.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:00: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170310_721994.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170310_721993.html) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170306_720355.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170306_720355.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170306_720356.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170306_720356.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170306_720357.html) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170306_720361.html) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201703/t20170306_720358.html) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170217_716254.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170217_716254.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:01: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170217_716198.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170217_716198.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:01: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715917.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715917.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715910.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715910.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715903.html) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715901.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715901.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715899.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170216_715899.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170213_714923.html) as HTTPError: HTTP Error 502: Bad Gateway
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170213_714921.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170213_714921.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713190.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713190.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:02: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713186.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713186.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:02: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:03: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713182.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:03: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713182.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:03: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:03: webpage_urlopen.py:53 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713180.html) as HTTPError(403-Forbidden): HTTP Error 403: Forbidden
ERROR: 03-16 17:00:03: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/Government/jcxxgk/zcwj/201702/t20170206_713180.html) as HTTPError: HTTP Error 403: Forbidden
ERROR: 03-16 17:00:03: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:03: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/../BottomNav/AboutUs/201309/t20130906_1027.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 17:00:03: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:03: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/../BottomNav/ContactUs/201309/t20130906_1029.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 17:00:03: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:03: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/../BottomNav/Help/201309/t20130930_113826.html) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 17:00:03: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
ERROR: 03-16 17:00:03: webpage_urlopen.py:62 * 35852 Fail to webpage_urlopen for url(http://www.nanning.gov.cn/../BottomNav/SiteMap/) as HTTPError: HTTP Error 400: Bad Request
ERROR: 03-16 17:00:03: readability.py:198 * 35852 error getting summary: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\readability\readability.py", line 155, in summary
    self._html(True)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 108, in _html
    self.html = self._parse(self.input)
  File "C:\Python27\lib\site-packages\readability\readability.py", line 117, in _parse
    doc, self.encoding = build_doc(input)
  File "C:\Python27\lib\site-packages\readability\htmls.py", line 21, in build_doc
    doc = lxml.html.document_fromstring(decoded_page.encode('utf-8', 'replace'), parser=utf8_parser)
  File "C:\Python27\lib\site-packages\lxml\html\__init__.py", line 600, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3032, in lxml.etree.fromstring (src\lxml\lxml.etree.c:68121)
  File "parser.pxi", line 1786, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:102470)
  File "parser.pxi", line 1674, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:101299)
  File "parser.pxi", line 1074, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:96481)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:91290)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:92476)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:91904)
XMLSyntaxError: line 131: htmlParseEntityRef: expecting ';'
